# Generated by Django 3.0.3 on 2020-04-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20200423_1457'),
        ('users', '0003_challenge_initial_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_initial_pitch',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
