# Generated by Django 3.0.3 on 2020-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_team_final_written_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_sign',
            field=models.BooleanField(default=False),
        ),
    ]
