# Generated by Django 3.0.3 on 2020-04-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_team_member_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member_sign',
        ),
    ]
