# Generated by Django 3.0.3 on 2020-04-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_team_signs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='signs',
        ),
    ]
