# Generated by Django 3.0.3 on 2020-04-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_team_signs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='signs',
        ),
        migrations.AddField(
            model_name='team',
            name='signs_member_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign1', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='signs_member_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign2', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='team',
            name='signs_member_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign3', to='users.Profile'),
        ),
    ]
