# Generated by Django 3.0.3 on 2020-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200428_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='signs_member_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='signs_member_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='signs_member_3',
        ),
        migrations.AddField(
            model_name='team',
            name='signs',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
