# Generated by Django 3.0.3 on 2020-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200428_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='challenge_owner_account',
            field=models.BooleanField(null=True),
        ),
    ]
