# Generated by Django 3.0.3 on 2020-05-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_challenge_apply_until_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_profile_challenge_owner_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_initial_pitch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_pitch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_teams', to='challenges.Challenge'),
        ),
    ]
