# Generated by Django 3.0.3 on 2020-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200505_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='challenge_owner_account',
            field=models.BooleanField(help_text='Selecting YES will allow you to submit challenges!, Selecting NO will allow you to solve a challenge', null=True),
        ),
    ]
