# Generated by Django 3.0.3 on 2020-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('assignor', models.CharField(max_length=50)),
                ('description_small', models.TextField()),
                ('description_large', models.TextField()),
                ('assignor_website', models.URLField()),
                ('due_date', models.DateField()),
                ('addmitted', models.BooleanField(blank=True, default=False)),
                ('applicants', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
