# Generated by Django 3.0.3 on 2020-04-22 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='applicants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
