# Generated by Django 3.0.3 on 2020-04-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20200422_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='addmitted',
            new_name='admitted',
        ),
    ]
