# Generated by Django 3.0.3 on 2020-04-22 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20200422_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
