# Generated by Django 3.0.3 on 2020-04-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20200422_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge_initial_pitch',
            name='challenge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
