# Generated by Django 3.0.3 on 2020-04-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_initial_pitch_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge_Initial_Pitch',
        ),
    ]
