# Generated by Django 3.0.3 on 2020-04-23 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0007_delete_challenge_initial_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
