# Generated by Django 3.0.3 on 2020-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20200423_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='contact_person_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='contact_person_full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='cover_image',
            field=models.ImageField(default='default_challenge.jpg', upload_to='challenge_pics'),
        ),
    ]
