# Generated by Django 3.0.3 on 2020-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20200425_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('admitted', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
