# Generated by Django 3.0.3 on 2020-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
