# Generated by Django 3.0.3 on 2020-04-29 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0013_auto_20200429_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='assignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
