# Generated by Django 3.0.3 on 2020-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_challenge_apply_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='apply_until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
