# Generated by Django 3.0.3 on 2020-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0021_challenge_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='cover_image',
            field=models.ImageField(default='default_challenge.png', upload_to='challenge_pics'),
        ),
    ]
