# Generated by Django 3.0.3 on 2020-05-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0023_auto_20200508_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='categories',
            field=models.CharField(choices=[('SW', 'Programming'), ('DE', 'Design'), ('HW', 'Hardware'), ('SC', 'Science'), ('MA', 'Marketing'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
