# Generated by Django 3.0.3 on 2020-05-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_auto_20200521_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='categories',
            new_name='category',
        ),
    ]
